#!/bin/bash
tail --lines=200 --sleep-interval=0.1 -F /var/log/apache2/other_vhosts_access.log |
    sed --unbuffered --regexp-extended '
        s/^.* (.*) - - \[(.*) .*\] "(.*) (.*) (.*)" ([0-9]*) (.*) "(.*)" "(.*)"$/\2 \1\t\3\t\6\t\7\t\x1b[36m\4\x1b[0m\t\x1b[35m\8\x1b[0m/;
        s/GET/GET /;
    ' |
    grep --line-buffered --invert-match --extended-regexp '\.(gif|jpeg|jpg|png|js|css|ico)|nagios|login\/refresh' |
    cut -c1-1000

