#!/bin/bash

for dir in $( (find af/*/.svn -maxdepth 0 | cut -f1-2 -d/ && find */.svn -maxdepth 0 | cut -f1 -d/) | sort); do
    info=$(svn info "$dir" | grep ^URL | cut -c6-)
    path=$(echo "$info" | cut -f9- -d/)
    date=$(svn info "$dir" | grep '^Last Changed Date' | cut -c20- | rev | cut -c26- | rev)
    
    printf "%-30s%-30s%-25s%-100s" "$dir" "$path" "$date" "$info"

    svn st "$dir" | grep -vE '^(-|$)' | cut -c-8 | sort | uniq -c | tr -d "\n"

    echo
done

